[package]
name = "redpowder"
version = "0.1.0"
authors = ["Jo√£o Victor joaonhk@gmail.com"]
edition = "2021"
description = "SDK / Devkit para Redstone OS"
license = "MIT"
repository = "https://github.com/redstone-os/redpowder"
